# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Brastlewark' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AxaTest
  pod 'SDWebImage'
  pod 'MultiSlider'
  pod 'SwinjectStoryboard'

  target 'BrastlewarkTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Mockingjay', :git => 'https://github.com/kylef/Mockingjay.git', :branch => 'master'
  end

  target 'BrastlewarkUITests' do
    # Pods for testing
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "11.0"
      end
    end
  end

end
