# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AxaTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AxaTest
  pod 'SDWebImage'
  pod 'MultiSlider'

  target 'AxaTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AxaTestUITests' do
    # Pods for testing
  end

end
